[snips]

; The folder that contains the snippet files.
; A path that starts at the program folder, for example: snips
; A full path also operates, for example: D:\Dropbox\snips
; Default: snips
folder=snips

; An autohotkey code that activates the snippets window.
; See https://autohotkey.com/docs/Hotkeys.htm#Symbols
; Default: ^`  = Ctrl + Backtick
; Example: ^+/  = Ctrl + Shift + Slash
key=^`

; Include category/folder name in quicksearch results
; Enabling will show ALL results if your typed search text
; matches a category/folder name.
; Default: Y
foldernamesearch=Y

; Where the window opens.
;   center  = the center of the screen
;   caret   = at the text cursor of the other program
;   mouse   = at the mouse pointer
; Default: center
position=center

; Read the snippet files again when the window opens, if a file changed.
; Set to N if you have many snippets and the window opens slowly.
; Default: Y
autorefresh=Y
